# -*- coding: utf-8 -*-
"""champion_poisson_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/197nth1Gzt6PEmtWNzrnBUUDg9Lqx7XKw
"""



"""# Predicting Annual Motor Insurance Claim Cost — SMM284 Group Report

This notebook is the full report and runs top to bottom. Data files go in `data/raw/` (adjust `DATA_DIR` below if needed).
"""

pip install pandas numpy matplotlib scikit-learn xgboost jupyter

from pathlib import Path
import warnings

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from sklearn.compose import ColumnTransformer
from sklearn.dummy import DummyRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import PoissonRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.model_selection import GroupKFold, cross_validate
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from xgboost import XGBRegressor

warnings.filterwarnings("ignore", category=FutureWarning)
RANDOM_STATE = 284  # fixed seed so results are the same every run
DATA_DIR = Path(".")

date_cols = ["Date_start_contract", "Date_last_renewal", "Date_next_renewal",
             "Date_birth", "Date_driving_licence", "Date_lapse"]
raw = pd.read_csv(DATA_DIR / "Motor vehicle insurance data.csv", sep=";")
for col in date_cols:
    raw[col] = pd.to_datetime(raw[col], dayfirst=True, errors="coerce")

print(f"{len(raw):,} rows, {raw.shape[1]} columns, {raw['ID'].nunique():,} unique customers")
raw.head(3)

"""## 3. Data cleaning and EDA"""

# --- Cleaning step 1: keep only rows that make logical sense ---
# Each rule is about impossible dates or amounts, never about how big the claims were,
# so this cannot leak outcome information into the model.
coverage_days = (raw["Date_next_renewal"] - raw["Date_last_renewal"]).dt.days
keep = (
    raw["Date_last_renewal"].notna()
    & raw["Date_next_renewal"].notna()
    & coverage_days.between(360, 370)                          # a record should cover ~1 year
    & (raw["Date_driving_licence"] <= raw["Date_last_renewal"])  # licence must exist before renewal
    & (raw["Date_start_contract"] <= raw["Date_last_renewal"])   # contract must start before renewal
    & (raw["Premium"] > 0)                                       # premium must be positive
    & (raw["Cost_claims_year"] >= 0)                             # cost cannot be negative
)
df = raw.loc[keep].copy()
print(f"Kept {len(df):,} rows, removed {(~keep).sum():,} illogical rows ({(~keep).mean():.2%})")

# --- Cleaning step 2: missing values ---
missing = df.isna().sum()
missing = missing[missing > 0].sort_values(ascending=False)
pd.DataFrame({"missing_n": missing, "missing_pct": (missing / len(df)).round(4)})

# --- Feature engineering: everything is measured at the renewal date ---
start = df["Date_last_renewal"]
df["Policy_year"] = start.dt.year
df["Age"] = (start - df["Date_birth"]).dt.days / 365.25
df["Licence_years"] = (start - df["Date_driving_licence"]).dt.days / 365.25
df["Vehicle_age"] = start.dt.year - df["Year_matriculation"]
df["Customer_years"] = (start - df["Date_start_contract"]).dt.days / 365.25
df["Length_missing"] = df["Length"].isna().astype(int)
df["Type_fuel"] = df["Type_fuel"].fillna("Unknown").astype(str)
# these columns hold category codes, not real numbers
for col in ["Distribution_channel", "Payment", "Type_risk", "Area", "Second_driver", "N_doors"]:
    df[col] = df[col].astype("Int64").astype(str)

df[["Policy_year", "Age", "Licence_years", "Vehicle_age", "Customer_years"]].describe().round(1)

# --- What does the target look like? ---
target = df["Cost_claims_year"]
positive = target[target > 0]
print(f"Policy-years with zero claim cost: {(target == 0).mean():.1%}")
print(f"Average annual claim cost (all rows): {target.mean():,.0f}")
print(f"Median cost when there IS a claim: {positive.median():,.0f}")
print(f"Biggest single annual cost: {positive.max():,.0f}")

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
axes[0].bar(["No claims", "Has claims"], [(target == 0).mean(), (target > 0).mean()], color=["#8aa6b8", "#d7834f"])
axes[0].set_ylabel("Share of policy-years")
axes[0].set_title("Most policies have zero claim cost")
axes[1].hist(np.log1p(positive), bins=40, color="#315b7d")
axes[1].set_xlabel("log(1 + claim cost), positive claims only")
axes[1].set_title("Claim costs are heavily right-skewed")
plt.tight_layout()
plt.show()

# --- Simple risk relationships ---
df["Age_band"] = pd.cut(df["Age"], [17, 25, 35, 45, 55, 65, 75, 101], right=False)
by_age = df.groupby("Age_band", observed=False)["Cost_claims_year"].mean()
by_risk = df.groupby("Type_risk")["Cost_claims_year"].mean()
by_year = df.groupby("Policy_year")["Cost_claims_year"].agg(policies="size", mean_cost="mean")
display(by_year.round(2))

fig, axes = plt.subplots(1, 2, figsize=(11, 4))
by_age.plot(kind="bar", ax=axes[0], color="#315b7d")
axes[0].set_title("Average claim cost by driver age")
axes[0].set_ylabel("Mean annual claim cost")
by_risk.plot(kind="bar", ax=axes[1], color="#d7834f")
axes[1].set_title("Average claim cost by vehicle risk type")
plt.tight_layout()
plt.show()

# --- Features, split, and preprocessing pipeline ---
NUMERIC = ["Age", "Licence_years", "Vehicle_age", "Customer_years",
           "Power", "Cylinder_capacity", "Length", "Weight", "Policies_in_force", "Length_missing"]
CATEGORICAL = ["Type_risk", "Type_fuel", "Area", "Distribution_channel",
               "Payment", "Second_driver", "N_doors"]
FEATURES = NUMERIC + CATEGORICAL

train = df[df["Policy_year"] <= 2017].copy()
test = df[df["Policy_year"] == 2018].copy()
X_train, y_train = train[FEATURES], train["Cost_claims_year"]
X_test, y_test = test[FEATURES], test["Cost_claims_year"]
print(f"Train: {len(train):,} rows (2015-2017) | Test: {len(test):,} rows (2018)")

# The pipeline fills missing values, scales numbers and one-hot encodes categories.
# Because it sits inside a Pipeline, it is re-fitted on the training part of every
# split automatically - the test data can never influence it.
preprocess = ColumnTransformer([
    ("num", Pipeline([("impute", SimpleImputer(strategy="median")),
                      ("scale", StandardScaler())]), NUMERIC),
    ("cat", Pipeline([("impute", SimpleImputer(strategy="most_frequent")),
                      ("onehot", OneHotEncoder(handle_unknown="ignore"))]), CATEGORICAL),
])

# --- The models ---
models = {
    "Baseline (predict the mean)": DummyRegressor(strategy="mean"),
    "Poisson GLM": PoissonRegressor(alpha=1.0, max_iter=500),
    "Random Forest (shallow)": RandomForestRegressor(
        n_estimators=200, max_depth=8, min_samples_leaf=60,
        random_state=RANDOM_STATE, n_jobs=-1),
    "Random Forest (deeper)": RandomForestRegressor(
        n_estimators=200, max_depth=14, min_samples_leaf=25,
        random_state=RANDOM_STATE, n_jobs=-1),
    "XGBoost (shallow)": XGBRegressor(
        n_estimators=300, learning_rate=0.05, max_depth=3, min_child_weight=20,
        subsample=0.8, colsample_bytree=0.8, random_state=RANDOM_STATE, n_jobs=-1),
    "XGBoost (deeper)": XGBRegressor(
        n_estimators=300, learning_rate=0.05, max_depth=5, min_child_weight=10,
        subsample=0.8, colsample_bytree=0.8, random_state=RANDOM_STATE, n_jobs=-1),
}

# --- 5-fold cross-validation on the training years, grouped by customer ---
cv = GroupKFold(n_splits=5)
scoring = {"MAE": "neg_mean_absolute_error", "RMSE": "neg_root_mean_squared_error", "R2": "r2"}

cv_rows = []
for name, model in models.items():
    pipe = Pipeline([("prep", preprocess), ("model", model)])
    scores = cross_validate(pipe, X_train, y_train, groups=train["ID"], cv=cv, scoring=scoring)
    cv_rows.append({
        "model": name,
        "CV MAE": -scores["test_MAE"].mean(),
        "CV RMSE": -scores["test_RMSE"].mean(),
        "CV R2": scores["test_R2"].mean(),
    })

cv_results = pd.DataFrame(cv_rows).sort_values("CV MAE")
cv_results.round(3)

# --- Final fit and one-time test evaluation ---
def keep_better(name_a, name_b):
    """Return whichever of the two model names had the lower cross-validated MAE."""
    sub = cv_results.set_index("model")
    return name_a if sub.loc[name_a, "CV MAE"] <= sub.loc[name_b, "CV MAE"] else name_b

final_names = [
    "Baseline (predict the mean)",
    "Poisson GLM",
    keep_better("Random Forest (shallow)", "Random Forest (deeper)"),
    keep_better("XGBoost (shallow)", "XGBoost (deeper)"),
]

fitted = {}
test_rows = []
for name in final_names:
    pipe = Pipeline([("prep", preprocess), ("model", models[name])])
    pipe.fit(X_train, y_train)
    pred = np.clip(pipe.predict(X_test), 0, None)
    fitted[name] = (pipe, pred)
    test_rows.append({
        "model": name,
        "MAE": mean_absolute_error(y_test, pred),
        "RMSE": mean_squared_error(y_test, pred) ** 0.5,
        "R2": r2_score(y_test, pred),
        "Predicted / Actual total": pred.sum() / y_test.sum(),
    })

test_results = pd.DataFrame(test_rows).sort_values("MAE")
test_results.round(3)

# --- Does the best model actually separate low-risk from high-risk policies? ---
# Sort test policies into 10 equal groups by predicted cost, then compare the
# ACTUAL average cost of each group. If the model works, actual cost should rise
# steadily from group 1 to group 10.
best_name = test_results.iloc[0]["model"] if test_results.iloc[0]["model"] != "Baseline (predict the mean)" else test_results.iloc[1]["model"]
best_pred = fitted[best_name][1]

groups = pd.DataFrame({"actual": y_test.values, "predicted": best_pred})
groups["risk_group"] = pd.qcut(groups["predicted"].rank(method="first"), 10, labels=False) + 1
lift = groups.groupby("risk_group").agg(policies=("actual", "size"),
                                        actual_mean=("actual", "mean"),
                                        predicted_mean=("predicted", "mean"))
lift["vs_portfolio_average"] = lift["actual_mean"] / y_test.mean()
display(lift.round(2))

fig, ax = plt.subplots(figsize=(8, 4))
ax.bar(lift.index, lift["actual_mean"], color="#315b7d")
ax.axhline(y_test.mean(), color="#d7834f", linestyle="--", label="Portfolio average")
ax.set_xlabel(f"Risk group by {best_name} prediction (1 = predicted safest)")
ax.set_ylabel("ACTUAL mean claim cost in 2018")
ax.set_title("Actual cost by predicted risk group")
ax.legend()
plt.tight_layout()
plt.show()

# --- Interpretation 1: which features matter to the best TREE model? ---
# The GLM won overall, but its interpretation comes from coefficients (next cell).
# Feature importance only exists for tree models, so we show the best of those.
tree_name = next(name for name in test_results["model"]
                 if "Forest" in name or "XGBoost" in name)
tree_pipe = fitted[tree_name][0]

feature_names = tree_pipe["prep"].get_feature_names_out()  # e.g. "num__Age", "cat__Type_risk_3"
importances = pd.Series(tree_pipe["model"].feature_importances_, index=feature_names)
top15 = importances.sort_values().tail(15)

fig, ax = plt.subplots(figsize=(8, 5))
ax.barh(top15.index, top15.values, color="#315b7d")
ax.set_xlabel("Feature importance")
ax.set_title(f"Top 15 features - {tree_name}")
plt.tight_layout()
plt.show()

# --- Interpretation 2: the GLM's coefficients (a transparent cross-check) ---
# Positive = higher expected cost, negative = lower. Numeric features are standardised,
# so coefficients show direction and relative strength, not exact money amounts.
glm_pipe = fitted["Poisson GLM"][0]
glm_coefs = pd.Series(glm_pipe["model"].coef_, index=glm_pipe["prep"].get_feature_names_out())
glm_coefs.reindex(glm_coefs.abs().sort_values(ascending=False).index).head(15).round(3).to_frame("coefficient")

# Is the best model similarly accurate across customer groups? (over/under-prediction check)
check = test.copy()
check["predicted"] = best_pred
check["Age_band"] = check["Age_band"].astype(str)
fairness = []
for col in ["Age_band", "Area", "Type_risk"]:
    g = check.groupby(col).agg(policies=("ID", "size"),
                               actual_total=("Cost_claims_year", "sum"),
                               predicted_total=("predicted", "sum"))
    g["actual / predicted"] = g["actual_total"] / g["predicted_total"]
    g.insert(0, "grouping", col)
    fairness.append(g.reset_index(names="group"))
pd.concat(fairness, ignore_index=True).round(2)

import joblib

# Grab the actual fitted Poisson GLM pipeline from your 'fitted' dictionary
champion_pipeline = fitted["Poisson GLM"][0]

# Save it as a portable model file
joblib.dump(champion_pipeline, "champion_poisson_model.pkl")
print("Model successfully exported!")